<h1 style="font-size: 40px;">Lab Exercises 4- Numpy and Pandas </h1>

<h1 style='font-size:30px'>1.Numpy  

In [5]:
'''
Task 1: Write a Numpy program to test whether none of the elements of a given array is zero.
'''
import numpy as np

a=np.arange(10)
print(a)
print(f'None of the elements are zero: {a.all()}')
print(f'Any of the elements are zero: {a.any()}')

[0 1 2 3 4 5 6 7 8 9]
None of the elements are zero: False
Any of the elements are zero: True


In [6]:
'''
Task 2: There are two arrays. 
The first array, array1 contains the values 45, 67, 23 
and array2 contains the values 56, 23, and 89. 
Write a Numpy program to create an element-wise comparison 
(greater, greater_equal, less and less_equal) of those two arrays.

'''
b=np.array([45,67,23])
c=np.array([56,23,89])
print(b>c)
print(b>=c)
print(b<c)
print(b<=c)

[False  True False]
[False  True False]
[ True False  True]
[ True False  True]


In [8]:
'''
Task3 Write a Numpy program to create an array of 8 zeros, 5 ones, 10 fives.
'''
a=np.zeros(8)
b=np.ones(5)
c=np.full(10,5) #numpy.full(shape, fill_value, dtype=None)
d=np.ones(10)*5
print(a)
print(b)
print(c)
print(d)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [9]:
'''
Task4: Write a Numpy program to add a vector v with values 2, 0, 2 to each row of a matrix m with 
values:
[23 45 11]
[12 23 54]
[29 19 34]
[1 23 10]
'''

v=np.array([2,0,2])
m=np.array([[23,45,11],[12,23,54],[29,19,34],[1,23,10]])
print(m+v)

[[25 45 13]
 [14 23 56]
 [31 19 36]
 [ 3 23 12]]


In [12]:
'''
Task 5: Write a NumPy program to create a 5x5 2d array with 1 on the border and 25 inside.
'''
d=np.ones((5,5),dtype=int)
d[1:-1,1:-1]=25
print(d)

[[ 1  1  1  1  1]
 [ 1 25 25 25  1]
 [ 1 25 25 25  1]
 [ 1 25 25 25  1]
 [ 1  1  1  1  1]]


In [14]:
'''
Task 6: Write a NumPy program to find common values between two arrays.
Array1 Array2
[23, 45, 11, 5] [23, 5, 1]
'''
a=np.array([23, 45, 11, 5])
b=np.array([23, 5, 1])
print(np.intersect1d(a,b))


[ 5 23]


In [25]:
'''
Task 7: Perform the following manipulation of the two arrays below: horizontal stacking, vertical 
stacking; divide the individual array horizontally and vertically.
Array1 Array2
[23, 45, 11]
[12, 23, 54]
[1, 23, 10]
[3, 5, 1]
[2, 3, 4]
[9, 1, 5]
'''
array1=np.array([[23, 45, 11],
                [12, 23, 54],
                [1,23,10]])
array2=np.array([[3, 5, 1],
                [2, 3, 4],
                [9, 1, 5]])
print(np.hstack((array1,array2)))
print(np.vstack((array1,array2)))
print(np.split(array1,3,axis=1))
print(np.split(array2,3,axis=0))

[[23 45 11  3  5  1]
 [12 23 54  2  3  4]
 [ 1 23 10  9  1  5]]
[[23 45 11]
 [12 23 54]
 [ 1 23 10]
 [ 3  5  1]
 [ 2  3  4]
 [ 9  1  5]]
[array([[23],
       [12],
       [ 1]]), array([[45],
       [23],
       [23]]), array([[11],
       [54],
       [10]])]
[array([[3, 5, 1]]), array([[2, 3, 4]]), array([[9, 1, 5]])]


In [ ]:
'''
Consider the following dataframe for the remaining tasks
Sample DataFrame:
assessment_results = {'name': ['Anastasia', 'Paul', 'Kathe', 'Joseph', 'Linda', 'Michael', 'Matt', 
'Laurentine', 'Chirstian', 'Jonas'],
'score': [12.5, 10, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

'''

In [33]:
import pandas as pd
'''
Task 8: Write a Pandas program to get the first 3 rows of a given DataFrame.
'''

assessment_results = {'name': ['Anastasia', 'Paul', 'Kathe', 'Joseph', 'Linda', 'Michael', 'Matt', 
'Laurentine', 'Chirstian', 'Jonas'],
'score': [12.5, 10, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
frame=pd.DataFrame(assessment_results,labels)
# frame.head(3)
frame[:3]

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Paul   10.0         3      no
c      Kathe   16.5         2     yes

In [34]:
'''
Task 9: Write a Pandas program to select the rows where the number of attempts in the 
examination is greater than 2.
'''
frame[frame['attempts']>2]

name  score  attempts qualify
b     Paul   10.0         3      no
d   Joseph    NaN         3      no
f  Michael   20.0         3     yes

In [36]:
'''
Task 10: Write a Pandas program to count the number of rows and columns of a DataFrame.
'''
frame.shape

(10, 4)

In [43]:
'''
Task 11: Write a Pandas program to select the rows the score is between 14 and 20 (inclusive).
'''
#frame[frame['score'].between(14,20)]
frame[(frame['score']>=14)&(frame['score']<=20)]
# Pandas中不能用and操作，要用&

name  score  attempts qualify
c    Kathe   16.5         2     yes
f  Michael   20.0         3     yes
g     Matt   14.5         1     yes
j    Jonas   19.0         1     yes

In [45]:
'''
Task 12: Write a Pandas program to change the score in row 'c' to 11.5
'''
frame.loc['c','score']=11.5
frame

name  score  attempts qualify
a   Anastasia   12.5         1     yes
b        Paul   10.0         3      no
c       Kathe   11.5         2     yes
d      Joseph    NaN         3      no
e       Linda    9.0         2      no
f     Michael   20.0         3     yes
g        Matt   14.5         1     yes
h  Laurentine    NaN         1      no
i   Chirstian    8.0         2      no
j       Jonas   19.0         1     yes

In [48]:
frame['c','score']=12

del frame['c','score']
frame

name  score  attempts qualify
a   Anastasia   12.5         1     yes
b        Paul   10.0         3      no
c       Kathe   11.5         2     yes
d      Joseph    NaN         3      no
e       Linda    9.0         2      no
f     Michael   20.0         3     yes
g        Matt   14.5         1     yes
h  Laurentine    NaN         1      no
i   Chirstian    8.0         2      no
j       Jonas   19.0         1     yes

In [49]:
'''
Task 13: Write a Pandas program to calculate the mean score for each different student in 
DataFrame
'''
print(np.mean(frame['score']))


13.0625
