<h1 style=font-size:40px>Self Attempt - Numpy</h1>

In [7]:
import numpy as np
new_array=np.array([1,2,3])
#new_array=np.array([0,2,3])
np.all(new_array) #np.all() returns True if all elements in the array are not zero, False otherwise.

np.True_

In [8]:
new_array=np.zeros(100)
print(new_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [10]:
import numpy as np
arr1=np.array([[5,4,1],[2,23,4],[3,5,1]])
arr2=np.array([[3,5,1],[5,3,4],[2,3,4]])
print(np.dot(arr1,arr2))   

[[ 37  40  25]
 [129  91 110]
 [ 36  33  27]]
