<h1 style=font-size:40px>Self Attempt - Numpy</h1>

In [2]:
import numpy as np
new_array=np.array([1,2,3])
#new_array=np.array([0,2,3])
np.all(new_array) #np.all() returns True if all elements in the array are not zero, False otherwise.

True

In [8]:
new_array=np.zeros(100)
print(new_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [11]:
import numpy as np
arr1=np.array([[5,4,1],
               [0,23,4],
               [3,5,1]])
arr2=np.array([[3,5,1],
               [5,3,4],
               [2,3,4]])
print(np.dot(arr1,arr2))   

[[ 37  40  25]
 [123  81 108]
 [ 36  33  27]]


In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#np.ones(10)
a=np.ones((3,3))


In [9]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(4,20,2)

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
np.arange(1,8,2).reshape(4,1)

array([[1],
       [3],
       [5],
       [7]])

In [16]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [20]:
np.random.randint(1,10,8).reshape(4,2)

array([[6, 2],
       [2, 1],
       [1, 4],
       [5, 6]])

In [23]:
a=np.arange(1,5)
b=np.arange(6,10)
print(a)
print(b)
a+b

[1 2 3 4]
[6 7 8 9]


array([ 7,  9, 11, 13])

In [24]:
a*b

array([ 6, 14, 24, 36])

In [25]:
np.dot(a,b)

80

In [29]:
a=np.reshape(a,(1,4))
np.dot(a,b)

array([80])

In [30]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [32]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [43]:
c=np.random.randint(1,10,12).reshape(3,4)  
print(c)

[[1 6 7 3]
 [4 5 4 6]
 [3 6 7 8]]


In [44]:
c=c.transpose()
print(c)
print(c.shape)

[[1 4 3]
 [6 5 6]
 [7 4 7]
 [3 6 8]]
(4, 3)


In [40]:
c=c.ravel()
print(c.shape)

(12,)


In [41]:
c=c.transpose()
print(c)
print(c.shape)

[5 4 5 7 5 9 5 2 1 6 7 9]
(12,)


In [47]:
a=np.random.randint(1,10,12).reshape(3,4)
b=np.random.randint(1,10,8).reshape(2,4)
np.vstack((a,b))

array([[8, 2, 4, 6],
       [2, 3, 5, 7],
       [8, 3, 5, 3],
       [1, 2, 7, 6],
       [8, 8, 2, 6]])

In [49]:
a=np.random.randint(1,10,12).reshape(4,3)
b=np.random.randint(1,10,8).reshape(4,2)
print(a)
print(b)
np.hstack((a,b))

[[7 6 3]
 [6 8 6]
 [1 9 5]
 [7 1 8]]
[[6 7]
 [1 3]
 [2 9]
 [5 3]]


array([[7, 6, 3, 6, 7],
       [6, 8, 6, 1, 3],
       [1, 9, 5, 2, 9],
       [7, 1, 8, 5, 3]])

In [51]:
A=np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
[B,C]=np.hsplit(A,2)
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [53]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [54]:
[D,E]=np.vsplit(A,2)
D

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [55]:
E

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
"""
The split() function allows us to split the array into nonsymmetrical parts.
Passing the array as an argument, you have to also specify the indexes of the part to be divided.
1) option axis =1 means the indexes will be the columns 
2) option axis = 0 means they will be the row indexes.

E.g. If we want to divide the matrix into three parts, the first part will include the first column, 
the second part will include the second and third column and the third part will include the last column

"""

A=np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
[A1,A2,A3]=np.split(A,[1,3],axis=0)
A1

array([[0, 1, 2, 3]])

In [62]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
A3

array([[12, 13, 14, 15]])

In [65]:
'''
we can leave it to numpy to manage the iteration using the apply_along_axis() function which takes 3 arguments: 
1)the aggregate function, 
2)the axis on which the iteration will be applied, 
3)the array. 
Example calculate the average values first by column then by row.

'''

def zhixing(x):
    return x+1

np.apply_along_axis(zhixing,0,A)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [66]:
print(np.__version__)

1.26.4


In [75]:
a=np.eye(10)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [76]:
print(np.all(a))

False


In [77]:
print(np.any(a)) 

True


In [72]:
a=np.zeros(100)

In [79]:
x=np.arange(100).reshape(10,10)
print(x)
header='col1 col2 col3 col4 col5 col6 col7 col8 col9 col10'
np.savetxt('temp.txt',x,fmt='%d',header=header)
result=np.loadtxt('temp.txt')
print(result)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
 [50. 51. 52. 53. 54. 55. 56. 57. 58. 59.]
 [60. 61. 62. 63. 64. 65. 66. 67. 68. 69.]
 [70. 71. 72. 73. 74. 75. 76. 77. 78. 79.]
 [80. 81. 82. 83. 84. 85. 86. 87. 88. 89.]
 [90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]]


In [81]:
data=np.random.randint(1,10,100).reshape(10,10)
np.save('test_data',data)
load_test_data=np.load('test_data.npy')
print(load_test_data)


[[1 7 1 7 9 3 6 4 6 6]
 [3 6 3 2 4 8 5 9 1 4]
 [3 3 7 6 5 3 6 1 3 1]
 [8 7 6 1 6 9 8 1 9 8]
 [3 5 3 6 9 1 9 4 5 8]
 [7 9 5 9 1 5 8 8 5 2]
 [4 9 9 1 6 4 1 2 8 9]
 [2 8 9 2 2 4 6 1 6 8]
 [2 7 9 5 5 6 9 1 3 4]
 [2 8 9 5 2 4 8 6 9 6]]


In [84]:
arr1=np.array([5,4,1,2,3,6])
arr2=arr1
arr3=arr1.copy()
print(arr2)

arr1[2]=0
print(arr1)
print(arr2)


print(arr3)

[5 4 1 2 3 6]
[5 4 0 2 3 6]
[5 4 0 2 3 6]
[5 4 1 2 3 6]
